import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { supabase } from '../../lib/supabase';
import { colors } from '../../lib/theme';

export default function Stock(){
 const router=useRouter();const [rows,setRows]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const load=async()=>{if(!supabase){setError('Supabase n’est pas encore configuré.');setLoading(false);return;}try{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/');return;}const r=await supabase.from('products').select('id,sku,name,color,stock,low_stock_threshold,active').eq('user_id',user.id).order('stock');if(r.error)throw r.error;setRows(r.data||[]);}catch(e:any){setError(e?.message||'Impossible de charger le stock.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const active=useMemo(()=>rows.filter(x=>x.active),[rows]);const total=active.reduce((s,x)=>s+x.stock,0);const low=active.filter(x=>x.stock<=x.low_stock_threshold);
 if(loading)return <View style={styles.center}><ActivityIndicator size="large" color={colors.blue2}/></View>;
 return <ScrollView style={styles.page} contentContainerStyle={styles.content}><View style={styles.head}><View><Text style={styles.eyebrow}>INVENTAIRE</Text><Text style={styles.title}>Stock</Text><Text style={styles.sub}>Surveillez les niveaux de stock en temps réel.</Text></View><Pressable onPress={()=>router.push('/(app)/products')} style={styles.button}><Text style={styles.buttonText}>Gérer les produits</Text></Pressable></View>{!!error&&<View style={styles.error}><Text style={styles.errorText}>{error}</Text></View>}<View style={styles.cards}><Card t="Produits actifs" v={String(active.length)}/><Card t="Unités en stock" v={String(total)}/><Card t="Stock faible" v={String(low.length)} alert={low.length>0}/></View><View style={styles.panel}><Text style={styles.panelTitle}>Niveaux de stock</Text>{active.map(p=><View key={p.id} style={styles.row}><View style={{flex:1}}><Text style={styles.name}>{p.name}</Text><Text style={styles.meta}>{p.sku}{p.color?` · ${p.color}`:''}</Text></View><Text style={[styles.stock,p.stock<=p.low_stock_threshold&&styles.low]}>{p.stock}</Text><Text style={styles.threshold}>seuil {p.low_stock_threshold}</Text></View>)}</View></ScrollView>
}
function Card({t,v,alert}:{t:string;v:string;alert?:boolean}){return <View style={styles.card}><Text style={styles.meta}>{t}</Text><Text style={[styles.value,alert&&styles.low]}>{v}</Text></View>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.bg},content:{padding:24,maxWidth:1400,width:'100%',alignSelf:'center'},center:{flex:1,backgroundColor:colors.bg,alignItems:'center',justifyContent:'center'},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:15,marginBottom:22},eyebrow:{color:colors.blue2,fontSize:10,fontWeight:'800',letterSpacing:2},title:{color:colors.text,fontSize:32,fontWeight:'900',marginTop:5},sub:{color:colors.muted,fontSize:14,marginTop:5},button:{minHeight:44,paddingHorizontal:15,borderRadius:10,borderColor:colors.border,borderWidth:1,justifyContent:'center'},buttonText:{color:colors.text,fontWeight:'700',fontSize:12},error:{padding:12,borderRadius:12,backgroundColor:'#451a1a',borderColor:'#7f1d1d',borderWidth:1},errorText:{color:'#fecaca'},cards:{flexDirection:'row',gap:10,marginBottom:16},card:{flex:1,backgroundColor:colors.surface,borderColor:colors.border,borderWidth:1,borderRadius:15,padding:16},meta:{color:colors.muted,fontSize:11},value:{color:colors.text,fontSize:24,fontWeight:'900',marginTop:6},panel:{backgroundColor:colors.surface,borderColor:colors.border,borderWidth:1,borderRadius:18,padding:18},panelTitle:{color:colors.text,fontSize:16,fontWeight:'800',marginBottom:6},row:{minHeight:65,borderTopColor:colors.border,borderTopWidth:1,flexDirection:'row',alignItems:'center',gap:15},name:{color:colors.text,fontSize:13,fontWeight:'800'},stock:{color:colors.text,fontSize:16,fontWeight:'900',width:45,textAlign:'right'},threshold:{color:colors.muted,fontSize:10,width:65},low:{color:'#fb923c'}})
